#!/bin/bash
# KinmuCore - 最終設定スクリプト（ブラウザで実行）

echo "🎉 KinmuCore デプロイ完了後の最終設定"
echo ""
echo "本番URL: https://kinmucore.vercel.app"
echo ""

# ==================================================
# ステップ1: Vercel GitHub連携
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 ステップ1: Vercel GitHub連携（自動デプロイ有効化）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "以下のURLをブラウザで開いて、GitHub連携を設定してください："
echo ""
echo "👉 https://vercel.com/morangokei-debugs-projects/kinmucore/settings/git"
echo ""
echo "手順:"
echo "  1. 上記URLにアクセス"
echo "  2. 「Connect Git Repository」をクリック"
echo "  3. 「GitHub」を選択"
echo "  4. 「morangokei-debug/KinmuCore」を選択"
echo "  5. 「Connect」をクリック"
echo ""
read -p "GitHub連携が完了したら Enter を押してください..."
echo ""
echo "✅ GitHub連携完了！"
echo "   これで git push するだけで自動デプロイされます。"
echo ""

# ==================================================
# ステップ2: Supabase リダイレクト設定
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 ステップ2: Supabase リダイレクト設定"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "以下のURLをブラウザで開いて、リダイレクトURLを設定してください："
echo ""
echo "👉 https://supabase.com/dashboard/project/gfkrdvdanebsvscefcll/auth/url-configuration"
echo ""
echo "設定内容:"
echo ""
echo "【Site URL】"
echo "  https://kinmucore.vercel.app"
echo ""
echo "【Redirect URLs】（既存のものに追加）"
echo "  https://kinmucore.vercel.app/auth/callback"
echo "  https://*.vercel.app/auth/callback"
echo ""
echo "手順:"
echo "  1. 上記URLにアクセス"
echo "  2. 「Site URL」に https://kinmucore.vercel.app を入力"
echo "  3. 「Redirect URLs」の「Add URL」をクリック"
echo "  4. https://kinmucore.vercel.app/auth/callback を追加"
echo "  5. もう一度「Add URL」をクリック"
echo "  6. https://*.vercel.app/auth/callback を追加"
echo "  7. 「Save」をクリック"
echo ""
read -p "Supabase設定が完了したら Enter を押してください..."
echo ""
echo "✅ Supabase設定完了！"
echo ""

# ==================================================
# 動作確認
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 動作確認"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "以下のURLで動作確認してください："
echo ""
echo "1. ログインページ:"
echo "   https://kinmucore.vercel.app/login"
echo ""
echo "2. ヘルスチェック:"
echo "   https://kinmucore.vercel.app/api/health"
echo ""
echo "3. 自動デプロイのテスト:"
echo "   cd ~/KinmuCore"
echo "   echo '# test' >> README.md"
echo "   git add README.md"
echo "   git commit -m 'Test auto-deploy'"
echo "   git push origin main"
echo ""
echo "   → Vercelダッシュボードで自動デプロイが始まることを確認"
echo "     https://vercel.com/morangokei-debugs-projects/kinmucore"
echo ""

# ==================================================
# 完了
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 全ての設定が完了しました！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 KinmuCore 本番環境情報"
echo ""
echo "  本番URL:          https://kinmucore.vercel.app"
echo "  Vercelプロジェクト: https://vercel.com/morangokei-debugs-projects/kinmucore"
echo "  GitHubリポジトリ:  https://github.com/morangokei-debug/KinmuCore"
echo "  Supabaseプロジェクト: https://gfkrdvdanebsvscefcll.supabase.co"
echo ""
echo "PharmBalanceと同じプラットフォーム（Vercel）で運用されています！"
echo ""
